// Generated by CoffeeScript 1.11.1

/*
Atrackt Tracking Library
https://github.com/brewster1134/atrackt
@version 1.0.10
@author Ryan Brewster
 */

(function() {
  (function(factory) {
    if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
      return define(['jquery'], function($) {
        return factory($);
      });
    } else {
      return factory(jQuery);
    }
  })(function($) {
    var Atrackt;
    Atrackt = (function() {
      function Atrackt() {}

      Atrackt.prototype.plugins = {};

      Atrackt.prototype._data = {};

      Atrackt.prototype._options = {};

      Atrackt.prototype._elements = {};

      Atrackt.prototype._callbacks = {};

      Atrackt.prototype.setPlugin = function(pluginName, plugin) {
        if (!pluginName) {
          throw new Error('ATRACKT ERROR: `setPlugin` - No plugin name defined');
        }
        if (!(plugin && typeof plugin.send === 'function')) {
          throw new Error("ATRACKT ERROR: `setPlugin` - No send method was defined for `" + pluginName + "`.");
        }
        pluginName = pluginName.toLowerCase().replace(/[^a-z]/g, '-');
        this.plugins[pluginName] = plugin;
        plugin.name = pluginName;
        plugin._data || (plugin._data = {});
        plugin._options || (plugin._options = {});
        plugin._elements || (plugin._elements = {});
        plugin._callbacks || (plugin._callbacks = {});
        plugin.setEvent = (function(_this) {
          return function(eventsObject) {
            return _this.setEvent(eventsObject, plugin);
          };
        })(this);
        plugin.setData = (function(_this) {
          return function(data) {
            return _this.setData(data, plugin);
          };
        })(this);
        plugin.setOptions = (function(_this) {
          return function(options) {
            return _this.setOptions(options, plugin);
          };
        })(this);
        plugin.setCallback = (function(_this) {
          return function(name, callback) {
            return _this.setCallback(name, callback, plugin);
          };
        })(this);
        return plugin.track = (function(_this) {
          return function(data, options, event, plugin) {
            return _this.track(data, options, event, plugin);
          };
        })(this);
      };

      Atrackt.prototype.setEvent = function(eventsObject, context) {
        var eventType, globalEvent, object, objects, pluginEvent, results;
        if (context == null) {
          context = this;
        }
        if (!eventsObject) {
          throw new Error('ATRACKT ERROR: `setEvent` - You must pass a valid event object.');
        }
        results = [];
        for (eventType in eventsObject) {
          objects = eventsObject[eventType];
          globalEvent = [eventType, 'atrackt'];
          pluginEvent = globalEvent.slice(0);
          if (context.name) {
            pluginEvent.push(context.name);
          }
          if (!(objects instanceof Array)) {
            objects = [objects];
          }
          results.push((function() {
            var i, len, results1;
            results1 = [];
            for (i = 0, len = objects.length; i < len; i++) {
              object = objects[i];
              results1.push($(object).each((function(_this) {
                return function(index, element) {
                  var base, base1, globalIndex, pluginData, pluginIndex, pluginName, ref, ref1, ref2, results2;
                  (base = _this._elements)[eventType] || (base[eventType] = []);
                  if (context.name) {
                    globalIndex = _this._elements[eventType].indexOf(element);
                    if (globalIndex === -1) {
                      (base1 = context._elements)[eventType] || (base1[eventType] = []);
                      if (context._elements[eventType].indexOf(element) === -1) {
                        return _this._registerElement(context, element, eventType);
                      }
                    }
                  } else if (_this._elements[eventType].indexOf(element) === -1) {
                    _this._registerElement(context, element, eventType);
                    ref = _this.plugins;
                    results2 = [];
                    for (pluginName in ref) {
                      pluginData = ref[pluginName];
                      pluginIndex = (ref1 = pluginData._elements[eventType]) != null ? ref1.indexOf(element) : void 0;
                      if (pluginIndex !== -1) {
                        results2.push((ref2 = pluginData._elements[eventType]) != null ? ref2.splice(pluginIndex, 1) : void 0);
                      } else {
                        results2.push(void 0);
                      }
                    }
                    return results2;
                  }
                };
              })(this)));
            }
            return results1;
          }).call(this));
        }
        return results;
      };

      Atrackt.prototype.setData = function(data, context) {
        if (context == null) {
          context = this;
        }
        return $.extend(true, context._data, data);
      };

      Atrackt.prototype.setOptions = function(options, context) {
        if (context == null) {
          context = this;
        }
        return $.extend(true, context._options, options);
      };

      Atrackt.prototype.setCallback = function(name, callback, context) {
        var allowedCallbacks, base;
        if (context == null) {
          context = this;
        }
        allowedCallbacks = ['before', 'after'];
        if (allowedCallbacks.indexOf(name) === -1) {
          throw new Error("ATRACKT ERROR: `setCallback` - `" + name + "` is not a valid callback.  Only callbacks allowed are: " + (allowedCallbacks.join(', ')));
        }
        (base = context._callbacks)[name] || (base[name] = []);
        return context._callbacks[name].push(callback);
      };

      Atrackt.prototype.track = function(data, options, event, context) {
        var delay, trackPlugins;
        if (options == null) {
          options = {};
        }
        if (context != null ? context.name : void 0) {
          options['_plugin'] = context.name;
        }
        trackPlugins = (function(_this) {
          return function() {
            var eventNamespace, pluginData, pluginName, ref, ref1, results;
            ref = _this.plugins;
            results = [];
            for (pluginName in ref) {
              pluginData = ref[pluginName];
              if (eventNamespace = event != null ? (ref1 = event.handleObj) != null ? ref1.namespace : void 0 : void 0) {
                if (eventNamespace === 'atrackt' || eventNamespace === ("atrackt." + pluginName)) {
                  results.push(_this._trackJqueryObject(pluginData, data, options, event));
                } else {
                  results.push(void 0);
                }
              } else {
                if (!options['_plugin'] || options['_plugin'] === pluginName) {
                  if (data instanceof jQuery) {
                    results.push(_this._trackJqueryObject(pluginData, data, options, event));
                  } else {
                    results.push(_this._track(pluginData, data, options, event));
                  }
                } else {
                  results.push(void 0);
                }
              }
            }
            return results;
          };
        })(this);
        delay = options['delay'];
        if (delay) {
          return setTimeout(function() {
            return trackPlugins();
          }, delay);
        } else {
          return trackPlugins();
        }
      };

      Atrackt.prototype._registerElement = function(context, element, eventType) {
        var globalEvent, pluginEvent;
        context._elements[eventType].push(element);
        globalEvent = [eventType, 'atrackt'];
        if (context.name) {
          pluginEvent = globalEvent.slice(0);
          if (context.name) {
            pluginEvent.push(context.name);
          }
        } else {
          pluginEvent = globalEvent;
        }
        $(element).off(globalEvent.join('.'));
        return $(element).on(pluginEvent.join('.'), function(e) {
          return context.track(this, {}, e);
        });
      };

      Atrackt.prototype._trackJqueryObject = function(plugin, data, options, event) {
        return $(data).each((function(_this) {
          return function(index, element) {
            return _this._track(plugin, element, options, event);
          };
        })(this));
      };

      Atrackt.prototype._track = function(plugin, data, options, event) {
        var callback, i, j, k, l, len, len1, len2, len3, metaData, optionsCopy, ref, ref1, ref2, ref3, results, trackingData, trackingOptions;
        metaData = this._getTrackObject(data, event);
        if (!metaData) {
          throw new Error('ATRACKT ERROR: `track` - Only valid selectors, jquery objects, or html nodes are supported.');
        }
        trackingData = $.extend(true, {}, this._data, plugin._data, options['_data'] || {}, metaData);
        optionsCopy = $.extend(true, {}, options, options[plugin.name] || {});
        delete optionsCopy['_data'];
        delete optionsCopy[plugin.name];
        trackingOptions = $.extend(true, {}, this._options, plugin._options, optionsCopy);
        ref = this._callbacks['before'] || [];
        for (i = 0, len = ref.length; i < len; i++) {
          callback = ref[i];
          if (typeof callback === "function") {
            callback(trackingData, trackingOptions);
          }
        }
        ref1 = plugin._callbacks['before'] || [];
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          callback = ref1[j];
          if (typeof callback === "function") {
            callback(trackingData, trackingOptions);
          }
        }
        if (data instanceof jQuery || data.nodeType === 1) {
          if (typeof $(data).data('atrackt-function') === 'function') {
            $.proxy($(data).data('atrackt-function'), data)(trackingData, trackingOptions);
          }
        }
        plugin.send(trackingData, trackingOptions);
        ref2 = plugin._callbacks['after'] || [];
        for (k = 0, len2 = ref2.length; k < len2; k++) {
          callback = ref2[k];
          if (typeof callback === "function") {
            callback(trackingData, trackingOptions);
          }
        }
        ref3 = this._callbacks['after'] || [];
        results = [];
        for (l = 0, len3 = ref3.length; l < len3; l++) {
          callback = ref3[l];
          results.push(typeof callback === "function" ? callback(trackingData, trackingOptions) : void 0);
        }
        return results;
      };

      Atrackt.prototype._getTrackObject = function(data, event) {
        var $el;
        if (data instanceof jQuery || data.nodeType === 1) {
          $el = $(data);
          data = {
            _categories: this._getCategories($el),
            _value: this._getValue($el)
          };
        }
        data['_location'] = this._getLocation();
        if (event != null ? event.type : void 0) {
          data['_event'] = event.type;
        }
        return data;
      };

      Atrackt.prototype._getLocation = function() {
        return $('body').data('atrackt-location') || $(document).attr('title') || document.URL;
      };

      Atrackt.prototype._getCategories = function($el) {
        var catArray;
        catArray = [];
        if ($el.data('atrackt-category')) {
          catArray.unshift($el.data('atrackt-category'));
        }
        $el.parents('[data-atrackt-category]').each(function() {
          return catArray.unshift($(this).data('atrackt-category'));
        });
        return catArray;
      };

      Atrackt.prototype._getValue = function($el) {
        return $el.data('atrackt-value') || $el.val() || $el.attr('title') || $el.attr('name') || $el.text().trim() || $el.attr('id') || $el.attr('class');
      };

      return Atrackt;

    })();
    return window.Atrackt || (window.Atrackt = new Atrackt);
  });

}).call(this);
