// Generated by CoffeeScript 2.2.4
(function () {
  /*
  Atrackt Tracking Library
  https://github.com/brewster1134/atrackt
  @version 1.0.0
  @author Ryan Brewster
  */
  (function (factory) {
    if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
      return define(['jquery', 'atrackt', 'jquery.scrollTo'], function ($, Atrackt) {
        return factory($, Atrackt.constructor);
      });
    } else {
      return factory(window.jQuery, window.Atrackt.constructor);
    }
  })(function ($, Atrackt) {
    var AtracktConsole;
    AtracktConsole = class AtracktConsole extends Atrackt {
      // Build the console html and add it to the dom

      constructor() {
        var consoleHtml;
        consoleHtml = "<div id=\"atrackt-console\">\n  <h4>Location: <span id=\"atrackt-location\"></span></h4>\n  <table>\n    <thead>\n      <tr>\n        <th>Plugin</th>\n        <th>Event</th>\n        <th>Categories</th>\n        <th>Value</th>\n      </tr>\n    </thead>\n    <tbody>\n    </tbody>\n  </table>\n<div>";
        super(consoleHtml);
        this.$console = $(consoleHtml);
        $('#atrackt-location', this.$console).text(this._getLocation());
        $('body').addClass('atrackt-console').prepend(this.$console);
        this._setPlugins();
        this._renderConsoleElements();
      }

      // Override the custom class to just log tracking data to the console

      setPlugin(pluginName, plugin) {
        super.setPlugin(pluginName, plugin);
        if (plugin) {
          // backup original send method and replace send with a simple console log
          plugin._send = plugin.send;
          return plugin.send = function (data, options) {
            return console.log(plugin.name, data, options);
          };
        }
      }

      _setPlugins() {
        var plugin, pluginName, ref, results;
        ref = this.plugins;
        results = [];
        for (pluginName in ref) {
          plugin = ref[pluginName];
          if (!plugin._send) {
            results.push(this.setPlugin(pluginName, plugin));
          } else {
            results.push(void 0);
          }
        }
        return results;
      }

      // Re-render console elements

      _renderConsoleElements() {
        var element, elements, eventType, i, len, plugin, pluginName, ref, ref1, results;
        $('tbody', this.$console).empty();
        ref = this._elements;
        // Render global elements
        for (eventType in ref) {
          elements = ref[eventType];
          for (i = 0, len = elements.length; i < len; i++) {
            element = elements[i];
            this._renderConsoleElement('ALL', element, eventType);
          }
        }
        ref1 = this.plugins;
        // Render all plugin elements
        results = [];
        for (pluginName in ref1) {
          plugin = ref1[pluginName];
          results.push(function () {
            var ref2, results1;
            ref2 = plugin._elements;
            results1 = [];
            for (eventType in ref2) {
              elements = ref2[eventType];
              results1.push(function () {
                var j, len1, results2;
                results2 = [];
                for (j = 0, len1 = elements.length; j < len1; j++) {
                  element = elements[j];
                  results2.push(this._renderConsoleElement(pluginName, element, eventType));
                }
                return results2;
              }.call(this));
            }
            return results1;
          }.call(this));
        }
        return results;
      }

      // Add console events to elements

      _registerElement(context, element, event) {
        var contextName;
        super._registerElement(context, element, event);
        contextName = context.name ? context.name : 'ALL';
        return this._renderConsoleElement(contextName, element, event);
      }

      // Add a single element to the console

      _renderConsoleElement(contextName, element, eventType) {
        var $rowEl, $trackEl, elementValueId, self, trackObject;
        self = this;
        // Get element meta data
        trackObject = this._getTrackObject(element, eventType);
        // Create unique id
        elementValueId = trackObject._categories.slice(0);
        elementValueId.unshift(trackObject._value);
        elementValueId.unshift(eventType);
        elementValueId = elementValueId.join('-').toLowerCase().replace(/[^a-z]/g, '');
        // Build console element html
        $rowEl = $(`<tr><td>${contextName}</td><td>${eventType}</td><td>${trackObject._categories}</td><td>${trackObject._value}</td></tr>`);
        $trackEl = $(element);
        // Add error class if elements track duplicate data
        if ($(`tr#${elementValueId}`, this.$console).length) {
          $(`tr#${elementValueId}`, this.$console).addClass('error');
          $rowEl.addClass('error');
        }
        // add row to console
        $('tbody', this.$console).append($rowEl);
        // Give id to both elements
        $rowEl.attr('id', elementValueId);
        $trackEl.attr('data-atrackt-id', elementValueId);
        // Add hover event to console element to highlight both the console and the tracked element
        return $rowEl.add($trackEl).hover(function () {
          $rowEl.addClass('atrackt-console-active');
          $trackEl.addClass('atrackt-console-active');
          // scroll to hovered element
          if ($.scrollTo) {
            if (this === $rowEl[0]) {
              return $.scrollTo($trackEl, 0, {
                offset: {
                  top: -300
                }
              });
            } else if (this === $trackEl[0]) {
              return self.$console.scrollTo($rowEl, 0, {
                offset: {
                  top: -100
                }
              });
            }
          }
        }, function () {
          $rowEl.removeClass('atrackt-console-active');
          return $trackEl.removeClass('atrackt-console-active');
        });
      }

    };
    if (location.href.indexOf('atracktConsole') > -1) {
      return window.Atrackt = new AtracktConsole();
    }
  });
}).call(this);