// Generated by CoffeeScript 1.8.0

/*
Atrackt Tracking Library
https://github.com/brewster1134/atrackt
@version 1.0.2
@author Ryan Brewster
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(root, factory) {
    if (location.href.indexOf('atracktConsole') > -1) {
      if (typeof define === 'function' && define.amd) {
        return define(['jquery', 'atrackt'], function($, Atrackt) {
          return window.Atrackt = new (factory($, Atrackt.constructor));
        });
      } else {
        return window.Atrackt = new (factory($, Atrackt.constructor));
      }
    }
  })(this, function($, Atrackt) {
    var AtracktConsole;
    return AtracktConsole = (function(_super) {
      __extends(AtracktConsole, _super);

      function AtracktConsole() {
        var consoleHtml;
        consoleHtml = "<div id=\"atrackt-console\">\n  <h4>Location: <span id=\"atrackt-location\"></span></h4>\n  <table>\n    <thead>\n      <tr>\n        <th>Plugin</th>\n        <th>Event</th>\n        <th>Categories</th>\n        <th>Value</th>\n      </tr>\n    </thead>\n    <tbody>\n    </tbody>\n  </table>\n<div>";
        this.$console = $(consoleHtml);
        $('#atrackt-location', this.$console).text(this._getLocation());
        $('body').addClass('atrackt-console').prepend(this.$console);
      }

      AtracktConsole.prototype.setPlugin = function(pluginName, plugin) {
        AtracktConsole.__super__.setPlugin.call(this, pluginName, plugin);
        if (plugin) {
          plugin._send = plugin.send;
          return plugin.send = function(data, options) {
            return console.log(plugin.name, data, options);
          };
        }
      };

      AtracktConsole.prototype._registerElement = function(context, element, event) {
        var contextName;
        AtracktConsole.__super__._registerElement.call(this, context, element, event);
        contextName = context.name ? context.name : 'ALL';
        return this._renderConsoleElement(contextName, element, event);
      };

      AtracktConsole.prototype._renderConsoleElement = function(contextName, element, eventType) {
        var $rowEl, $trackEl, elementValueId, trackObject;
        trackObject = this._getTrackObject(element, eventType);
        elementValueId = trackObject._categories.slice(0);
        elementValueId.unshift(trackObject._value);
        elementValueId.unshift(eventType);
        elementValueId = elementValueId.join('-').toLowerCase().replace(/[^a-z]/g, '');
        $rowEl = $("<tr><td>" + contextName + "</td><td>" + eventType + "</td><td>" + trackObject._categories + "</td><td>" + trackObject._value + "</td></tr>");
        $trackEl = $(element);
        if ($("tr#" + elementValueId, this.$console).length) {
          $("tr#" + elementValueId, this.$console).addClass('error');
          $rowEl.addClass('error');
        }
        $('tbody', this.$console).append($rowEl);
        $rowEl.attr('id', elementValueId);
        $trackEl.attr('data-atrackt-id', elementValueId);
        return $rowEl.add($trackEl).hover(function() {
          $rowEl.addClass('atrackt-console-active');
          return $trackEl.addClass('atrackt-console-active');
        }, function() {
          $rowEl.removeClass('atrackt-console-active');
          return $trackEl.removeClass('atrackt-console-active');
        });
      };

      return AtracktConsole;

    })(Atrackt);
  });

}).call(this);
